<a href="https://colab.research.google.com/github/PriscillaHandoyo/learn-python/blob/main/session01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
train_df = pd.read_csv("/content/train.csv")
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
train_df.shape

(891, 12)

1. How many passanger is under 22 years old?

In [27]:
train_df["Age"].isnull().value_counts()

Age
False    714
True     177
Name: count, dtype: int64

There are about 177 null values in the Age column. Missing ages count as `False` in the comparision, so they're left out

In [24]:
not_adults = (train_df["Age"] < 22.0).sum()
# use .sum() not .count() because .count() returns the total number of rows in
# the column and doesn't look at the condition
print("Passanger that are not an adult:", not_adults)

Passanger that are not an adult: 204

2. Did woman survive more than men?

In [30]:
survivor = train_df.groupby("Sex")["Survived"].mean()
# to displayed the value of both sex and survived, use value_counts()
# if we use count() it will only displayed the value of the first column and
# the total of the second
# raw counts can mislead. to compare groups of different sizes, we need rate,
# use .mean() (shorter way of doing normalize=true to find rate). survived can
# use the shorter way because `Survived` is 1s and 0s, so its mean is the survival rate
survivor

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

3. Survival rate by sex and class together

In [ ]:
survival_rate = train_df.groupby(['Sex', 'Pclass'])['Survived'].value_counts(normalize=True)
# use normalize=True to get percentage
survival_rate

Sex     Pclass  Survived
female  1       1           0.968085
                0           0.031915
        2       1           0.921053
                0           0.078947
        3       0           0.500000
                1           0.500000
male    1       0           0.631148
                1           0.368852
        2       0           0.842593
                1           0.157407
        3       0           0.864553
                1           0.135447
Name: proportion, dtype: float64

4. Did people who paid more survived more?

In [40]:
survived_fare = train_df.groupby(["Fare"])["Survived"].mean()
survived_fare.sort_values(ascending=False).head()

Fare
7.1417    1.0
8.1125    1.0
8.5167    1.0
8.6833    1.0
8.0292    1.0
Name: Survived, dtype: float64

5. Did more people travel alone or with families?

In [62]:
total_pass = train_df["Name"].count()
print("Total passangers on board:", total_pass)

train_df["alone"] = train_df["SibSp"] + train_df["Parch"]
alone = (train_df["alone"] == 0).sum()
print("Total passangers on baord that come alone:", alone)

Total passangers on board: 891
Total passangers on baord that come alone: 537